#ifndef SG_GLOBAL_SETTINGS 
#define SG_GLOBAL_SETTINGS

#define WINDOW_WIDTH 1024
#define WINDOW_HEIGHT 768

#define GLOBAL_SCALE 0.5

#define HERO_RESOURCE_JSON_FILE "Hero_Res.json"
#define SKIRMISH_SCENE_SWITCH_TEXT_JSON_FILE "SwitchSceneText.json"
#define MENU_ITEM_TEXT_JSON_FILE "Menu.json"
#define INFO_TEXT_JSON_FILE "Info.json"
#define HERO_INFO_TEXT_JSON_FILE "HeroInfoText.json"
#define WEAPON_REPO_TEXT_JSON_FILE "WeaponInfoText.json"
#define CORPS_REPO_TEXT_JSON_FILE "CorpsInfoText.json"

#define SG_DRAMA_SCENE_HERO_RES_PATH "DramaSceneObjects/"
#define SG_HERO_FACE_RES_PATH "HeroFaces/"
#define SG_SKIRMISH_SCENE_HERO_RES_PATH "SkirmishSceneObjects/"
#define SG_SKIRMISH_SCENE_HERO_ATTACK_RES_PATH "HeroAttack/"
#define SG_SKIRMISH_SCENE_HERO_SPEC_RES_PATH "HeroSpecAction/"
#define SG_SKIRMISH_SCENE_OBJ_RES_PATH "Mark/"
#define SG_SKIRMISH_SCENE_MAGIC_CALL_RES_PATH "Magic/"
#define SG_WEAPON_REPO_RES_PATH "WeaponRepo/"
#define SG_LUA_SCRIPTS_PATH "Scripts/"
#define SG_SKIRMISH_SCENE_HERO_WALK_RES_WIDTH 48
#define SG_SKIRMISH_SCENE_HERO_WALK_RES_HEIGHT 48

#define SG_SKIRMISH_SCENE_HERO_ATTACK_RES_WIDTH 64
#define SG_SKIRMISH_SCENE_HERO_ATTACK_RES_HEIGHT 64

#define SG_SKIRMISH_SCENE_MAGIC_CALL_RES_WIDTH 300
#define SG_SKIRMISH_SCENE_MAGIC_CALL_RES_HEIGHT 300

#define SG_SKIRMISH_SCENE_HERO_SPEC_RES_WIDTH 48
#define SG_SKIRMISH_SCENE_HERO_SPEC_RES_HEIGHT 48

#define SG_WEAPON_ITEM_RES_PATH "WeaponRepo/"
#define SG_WEAPON_ITEM_RES_WIDTH 32
#define SG_WEAPON_ITEM_RES_HEIGHT 32

#define HERO_DRAMA_RES_WIDTH 48
#define HERO_DRAMA_RES_HEIGHT 64

#define DIALOG_WINDOW_BACKGROUND "Mark/DialogWindowTexture.png"
#define SELECT_WINDOW_BACKGROUND "Mark/SelectWindowTexture.png"

#define INFO_PANEL_BACKGROUND "Mark/lambskin.jpg"

#define DIAGLOG_WINDOW_ARROW_UP "Mark/speakDialogArrowUp.png"
#define SG_SKIRMISH_SCENE_HERO_STATUS_CHAOS "Mark/chaos.png"

#define SG_SKIRMISH_AREA_PATH "path"
#define SG_SKIRMISH_AREA_ATTACK "attack"

#define TEXT_FONT_NAME "fonts/libian.ttf"
#define TEXT_FONT_SIZE 20
#define CHAPTER_TEXT_FONT_SIZE 50
#endif