#ifndef SG_GLOBAL_SETTINGS 
#define SG_GLOBAL_SETTINGS

#define WINDOW_WIDTH 1024
#define WINDOW_HEIGHT 768

#define HERO_RESOURCE_JSON_FILE "HeroRes.json"
#define SKIRMISH_SCENE_SWITCH_TEXT_JSON_FILE "SwitchSceneText.json"

#define SG_DRAMA_SCENE_HERO_RES_PATH "DramaSceneObjects/"
#define SG_HERO_FACE_RES_PATH "HeroFaces/"
#define SG_SKIRMISH_SCENE_HERO_RES_PATH "SkirmishSceneObjects/"
#define SG_SKIRMISH_SCENE_HERO_ATTACK_RES_PATH "HeroAttack/"
#define SG_SKIRMISH_SCENE_HERO_SPEC_RES_PATH "HeroSpecAction/"
#define SG_SKIRMISH_SCENE_OBJ_RES_PATH "Mark/"
#define SG_SKIRMISH_SCENE_MAGIC_CALL_RES_PATH "Magic/"

#define SG_SKIRMISH_SCENE_HERO_WALK_RES_WIDTH 48
#define SG_SKIRMISH_SCENE_HERO_WALK_RES_HEIGHT 48

#define SG_SKIRMISH_SCENE_HERO_ATTACK_RES_WIDTH 64
#define SG_SKIRMISH_SCENE_HERO_ATTACK_RES_HEIGHT 64

#define SG_SKIRMISH_SCENE_MAGIC_CALL_RES_WIDTH 300
#define SG_SKIRMISH_SCENE_MAGIC_CALL_RES_HEIGHT 300

#define SG_SKIRMISH_SCENE_HERO_SPEC_RES_WIDTH 48
#define SG_SKIRMISH_SCENE_HERO_SPEC_RES_HEIGHT 48

#define HERO_DRAMA_RES_WIDTH 48
#define HERO_DRAMA_RES_HEIGHT 64

#define DIALOG_WINDOW_BACKGROUND "Mark/DialogWindowTexture.png"
#define SELECT_WINDOW_BACKGROUND "Mark/SelectWindowTexture.png"

#define DIAGLOG_WINDOW_ARROW_UP "Mark/speakDialogArrowUp.png"

#define TEXT_FONT_NAME "Microsoft YaHei"
#define TEXT_FONT_SIZE 20
#define CHAPTER_TEXT_FONT_SIZE 50
#endif