#ifndef SGS_TIME_INTERVAL_H
#define SGS_TIME_INTERVAL_H

#define SGS_HERO_MOVE_ONE_STEP_TIME 0.8f

#define SGS_HERO_ATTACK_ACTION_INTERVAL 0.2f

#define SGS_HERO_ATTACK_ACTION_FRAME_NUM 4

#define SGS_HERO_ATTACK_ACTION_DURATION ((SGS_HERO_ATTACK_ACTION_INTERVAL)*(SGS_HERO_ATTACK_ACTION_FRAME_NUM))

#endif